### ISSUE TITLE
Rename project

### ISSUE THREAD

**Issue by cmckni3** [andyperlitch/ngx-super-table#10]
Would you be open to renaming the project to `ngx-super-table`?

See https://juristr.com/blog/2016/12/let-me-explain-angular-release-cycles/ about the release cycles and how everything will be simply called `Angular` instead of `Angular 2` or `Angular 4`. Some other projects taken the approach of saying `Angular X` instead of `Angular 2+`, `Angular 4`, etc.

**Comment by cmckni3** [comment]
Should probably rename after rolling out the fixes for the library to work in 2.4.

**Comment by andy-because** [comment]
Excellent suggestion, Chris! The whole differentiation between angular and angularJS is _such_ a headache... I like the `ngx-` prefix convention. I'll review your PR tonight/tomorrow, then after we merge it, let's tackle this.

**Comment by andyperlitch** [comment]
Excellent suggestion, Chris! The whole differentiation between angular and angularJS is _such_ a headache... I like the `ngx-` prefix convention. I'll review your PR tonight/tomorrow, then after we merge it, let's tackle this.

**Comment by cmckni3** [comment]
Yeah, it makes Google searches impossible haha. I am glad Joe Eames et al. created [ngDoc](http://ngdoc.io/)

**Comment by andyperlitch** [comment]
oOo this is a new site for me... thanks!

**Comment by andyperlitch** [comment]
Hey @cmckni3,

I have renamed all necessary files and successfully ran the demo. I have also added you as a collaborator.

I am having some difficulty running `npm run release`. I'll open a new issue with publishing.

**Comment by cmckni3** [comment]
Thanks!

Oops, I forgot to update the build script. I copied over the `angular/cli` build script instead haha.

**Comment by cmckni3** [comment]
Are you on Windows @andyperlitch? I'm not sure those scripts will work unless you use Ubuntu on Windows.

**Comment by andyperlitch** [comment]
nope, i am on mac

**Comment by cmckni3** [comment]
Should work on Linux and Mac
