### ISSUE TITLE
rollup warning

### ISSUE THREAD

**Issue by cmckni3** [andyperlitch/ngx-super-table#14]
rollup returns the following [warning](https://github.com/rollup/rollup/wiki/Troubleshooting#this-is-undefined) in a few files. I think it has to do with the files that contain loose variables at the top of the file.

```
⚠️   The 'this' keyword is equivalent to 'undefined' at the top level of an ES module, and has been rewritten
https://github.com/rollup/rollup/wiki/Troubleshooting#this-is-undefined
```

**Comment by cmckni3** [comment]
This shouldn't have been closed. I think GitHub picked up "Doesn't fix" haha.

**Comment by andyperlitch** [comment]
lol

**Comment by cmckni3** [comment]
Appears to have been fixed.

**Comment by andyperlitch** [comment]
nice!
