### ISSUE TITLE
Setup travis-ci?

### ISSUE THREAD

**Issue by cmckni3** [andyperlitch/ngx-super-table#16]

**Comment by cmckni3** [comment]
@andyperlitch can you give me access to the Travis CI project? I can automate the `gh-pages` and reduce the amount of bloat in the repo.

**Comment by andyperlitch** [comment]
I just enabled it and triggered the first build. Now I'm looking for permissions settings but am not seeing it on the travis UI. Any thoughts?

**Comment by cmckni3** [comment]
I can actually see the settings on Travis CI so I have the permissions for it now.

Thanks!

**Comment by cmckni3** [comment]
Working on getting Chrome Headless running in Travis CI. Doesn't seem to be too bad.

**Comment by cmckni3** [comment]
Auto deploy is setup now. I used a personal access token of my own in the secret variables of Travis. It only has public repo access.
