### ISSUE TITLE
Demo link => 404 File not found

### ISSUE THREAD

**Issue by vajdajana** [andyperlitch/ngx-super-table#23]
https://andyperlitch.github.io/ngx-super-table/demo/
=> 404 File not found

**Comment by niralmunjariya** [comment]
Is anyone maintaining this project?

**Comment by cmckni3** [comment]
Yes, @andyperlitch and I are maintaining it. It has been almost a month but I am working on some refactoring. New features will come down the road as well.

@vajdajana @niralmunjariya Unforunately, I don't have access to repo settings but I am looking into this.

**Comment by cmckni3** [comment]
Give the demo a shot now @vajdajana and @niralmunjariya

**Comment by cmckni3** [comment]
Apologies but the build process for everything is still a work in progress.
