### ISSUE TITLE
String filter not working properly when the result is 1 value

### ISSUE THREAD

**Issue by poblouin** [andyperlitch/ngx-super-table#28]
I think I may have found an issue with the string filter.

See this example below:

I'm filtering some name, applying the filter "sea_ga_en_generic_" and here's the result, this is fine.

![screenshot from 2017-09-19 13-35-00](https://user-images.githubusercontent.com/7467410/30606455-c9d74e68-9d3f-11e7-87bf-9aa503c4701a.png)

I apply the filter applying the filter "sea_ga_en_generic_e" and now only 2 results are shown, this is still fine.

![screenshot from 2017-09-19 13-45-40](https://user-images.githubusercontent.com/7467410/30606788-e1fe4d92-9d40-11e7-8216-cd55db5791fa.png)

Now I apply the filter "sea_ga_en_generic_t" which match only one name "sea_ga_en_generic_test-heavy-up" and nothing is displayed. Even if I apply the filter "=sea_ga_en_generic_test-heavy-up" nothing is shown, but obviously 1 row should be displayed.

![screenshot from 2017-09-19 13-45-52](https://user-images.githubusercontent.com/7467410/30606794-e56dc9b2-9d40-11e7-93ae-20e15eeaa0cb.png)

The filter on my column is superTableFilters.STRING, I did not overwrite anything.

Any idea what the problem could be? Thanks!

**Comment by cmckni3** [comment]
I will have to recreate it in the demo locally unless you want to create a plunkr.

My initial investigation shows the filter function seems to behave correctly.

**Comment by poblouin** [comment]
@cmckni3 I'll do my best to provide you a sample asap, I'm quite on a tight schedule right now, but I'm pretty sure there is a problem with the filter. 

Take a look at this use case I just found:

1. Filtering with "sea_ga_en_generic_" it shows this:

![screenshot from 2017-09-19 17-31-46](https://user-images.githubusercontent.com/7467410/30616603-c366abde-9d60-11e7-914e-e7b2047dcf13.png)

Look at the last 3 results. Filtering with "sea_ga_en_generic_**e**" should show 3 results, but it only shows 2 (missing the last row of the first screenshot):

![screenshot from 2017-09-19 17-31-58](https://user-images.githubusercontent.com/7467410/30616623-da49221e-9d60-11e7-91ac-3473d5ed9ff2.png)

There seem to always be missing a row when filtering, that would explain why no results are shown when applying a filter that should show 1 value.

I'll try to send you a plunkr by the end of the week.

**Comment by cmckni3** [comment]
@poblouin Try with master. I don't have access to npmjs but @andyperlitch can release at some point.

**Comment by cmckni3** [comment]
Was an off by error. I reproduced it with datasets that fit entirely on my screen while filtering and when not filtering.

**Comment by poblouin** [comment]
Alright thank you for the quick response, I'll try with the master tomorrow and see if it solves my issue.

**Comment by cmckni3** [comment]
No problem.
