### ISSUE TITLE
chore: Update to 2.0.0

### ISSUE THREAD

**Issue by RicardoVaranda** [andyperlitch/ngx-super-table#3]
This component is not working as of 2.0.0 due to the the addition of NgModule.

**Comment by andyperlitch** [comment]
Thanks for this, will check it out.

**Comment by tscislo** [comment]
+1

**Comment by andyperlitch** [comment]
@RicardoVaranda @tscislo I'm looking at the docs for the new @NgModule decorator and frankly I'm pretty confused as to how I should upgrade. From what I gather, I need to move all the `directives: [...]` to a top-level @NgModule... but how does that transfer to a third-party lib like this one? Should the third party lib export an @NgModule?

**Comment by tscislo** [comment]
Yes a 3rd party lib should export @NgModule which then can be used as a dependency in other people's modules. Your @NgModule should export all components that you think users might want to use.

**Comment by PatrickHuetter** [comment]
+1

**Comment by andyperlitch** [comment]
Just an update for you guys... I've been going through the process of updating to GA 2.0, but am running into an issue with enum filters that essentially requires [this functionality](http://stackoverflow.com/questions/39137268/angular2-render-component-to-body/39798285#39798285), and hoping someone can help out with that. Stay tuned

**Comment by andyperlitch** [comment]
I took some more time to try and get this working (branch [update-2.0.0#3](https://github.com/andyperlitch/ng2-super-table/tree/update-2.0.0%233)), but am royally stumped. And frankly, a little ticked off at the angular team for making so many breaking changes so late in the RC process. This whole `@NgModule` thing feels very sloppy and cumbersome to me. I think I am missing the point here. Before this, it seemed so clean -- define a component, specify the components that it depends on, export public components. Now it seems like everything has to now also be wrapped in an @NgModule. And you can't specify dependencies on a component level. And its way more difficult to manually compile and insert a component into the DOM.

As I am no longer planning to use angular2 in the near future, I am going to move on from trying to get this to work. Again, if someone wants to take up the baton and try their hand and making this work, PRs are welcome and appreciated.

**Comment by RicardoVaranda** [comment]
Thanks for the feed back,  I'M actually quite familiar with this due to using angular cli, I'll have a look at it once I've time.

**Comment by sante85** [comment]
Hi developer, how to resolve problems to branch update-2.0.0#3 for transfer to angular 2.0?

**Comment by andyperlitch** [comment]
@sante85 I'm still hoping for community help on this issue, as I haven't yet figured out how to migrate to 2.0. Perhaps a friendly ping to @RicardoVaranda may work 👍

**Comment by webia1** [comment]
That's a really pretty good library and should go the way to Angular2,.. I would help, cannot get away from current project, but [there is a great NG2 community,](https://github.com/mgechev/angular-seed/graphs/contributors) maybe they have some more time,..

**Comment by cmckni3** [comment]
I believe I have resolved a lot of the issues for updating to Angular 2.3. There's something wrong with the webpack setup though.

Do you want to use webpack 2 or switch to @angular/cli @webia1?

**Comment by andyperlitch** [comment]
@cmckni3 thanks a lot for this! I am not married to webpack at all... my main concern is making this package functional. I'll gladly review any PR you submit as timely as I can.

**Comment by cmckni3** [comment]
Started porting it over to @angular/cli. Hopefully, I can finish it this weekend.

**Comment by grugknuckle** [comment]
@cmckni3 I can't wait to see what you come up with. This is a great library and I wan't to use it in my angular 2.4.10 app.

**Comment by bhaskarvyas001** [comment]
is it done?

**Comment by andyperlitch** [comment]
No word yet from @cmckni3, would still _really_ appreciate any work he has done on it.

I have started a more serious angular project that requires this, and may get around to resolving this in the next few weeks.

**Comment by cmckni3** [comment]
I am close to being finished. Making some final fixes involving creating components.

Last piece is going to be some publishing scripts.

**Comment by cmckni3** [comment]
PR #9 

Just need to work out the publishing scripts.

Should probably publish the update for 2.0-2.4 and then update for 4.0.

**Comment by andy-because** [comment]
You are **awesome**, Chris! I'll take a look tonight/tomorrow and we'll bring this project back to life 👍

**Comment by andyperlitch** [comment]
You are **awesome**, Chris! I'll take a look tonight/tomorrow and we'll bring this project back to life 👍

**Comment by cmckni3** [comment]
No problem. I will probably look into finishing up the build scripts tomorrow.

I may hold off on trying to fix the cli issues with `lodash`.
