### ISSUE TITLE
ngx-super-table has no exported member 'SuperTableColumn'

### ISSUE THREAD

**Issue by laureD2SI** [andyperlitch/ngx-super-table#33]
Running the demo I get
```Module '".../frontend/node_modules/ngx-super-table/index"' has no exported member 'SuperTableColumn'```
Could not find it in the repo.

**Comment by cmckni3** [comment]
The `I` prefixes were recently removed and the updated code hasn't been published to npmjs.org.

I added a note of this change in the README

**Comment by Paul75** [comment]
For me the last version SuperTableColumn not found again ...

**Comment by cmckni3** [comment]
@Paul75 I don't have access to update npm so the change hasn't been push to the npm registry. See https://github.com/andyperlitch/ngx-super-table/pull/30 for the old prefixes that the npm package contains.
