### ISSUE TITLE
Getting an error when creating a build via "ng build --prod"

### ISSUE THREAD

**Issue by submetu** [andyperlitch/ngx-super-table#39]
ERROR: 
ERROR in node_modules/ngx-super-table/superTableRow.component.d.ts.SuperTableRow.html(1,5): : Property 'state' is private and only accessible within class 'SuperTableRow'.
node_modules/ngx-super-table/enumFilter.component.d.ts.EnumFilter.html(5,7): : Expected 0 arguments, but got 1.

Any idea what can be the reason?

**Comment by cmckni3** [comment]
Hmm, I see the issues in the code on master. I am going to work on setting up `ng-packagr` to catch these issues before release.

**Comment by submetu** [comment]
How long will it going to take? any ideas?
We were gonna use this library in production soon.

**Comment by cmckni3** [comment]
What does your `tsconfig.json` file look like? It should already work as long as `noImplicitAny` is set to false.

**Comment by cmckni3** [comment]
Also, the first issue was fixed on August 2nd, 2017 but never published to npmjs.org. I don't have access to the package on npmjs.org.

@andyperlitch

**Comment by cmckni3** [comment]
Sending a PR with `ng-packagr` soon @andyperlitch and @submetu

**Comment by submetu** [comment]
Any updates?

**Comment by cmckni3** [comment]
I merged in the PR but still don't have access to npmjs.org. It should build without AOT.
