### ISSUE TITLE
How to install SuperTable ?

### ISSUE THREAD

**Issue by pierre-luc** [andyperlitch/ngx-super-table#7]
I try to install the beautiful ng2-super-table in my project but if I add directives: [SuperTable] in @Component decorator I get this error:

Argument of type '{ selector: string; directives: typeof SuperTable[]; templateUrl: string; styleUrls: string[]; }' is not assignable to parameter of type 'Component'.
  Object literal may only specify known properties, and 'directives' does not exist in type 'Component'.

And I don't found SuperTableModule in your project, so I can't use SuperTable in my project.

I use angular 4.0.0

**Comment by cmckni3** [comment]
I am going to check 4.0.0 compatibility shortly. Support for version 2.0.0 was just finished in #9.

**Comment by cmckni3** [comment]
@pierre-luc master now works with Angular version 2.0 and above. I tried it in a project running version 4.3 and it works. #18 will peer dependency warnings.

Closing this issue but feel free to post issues with the new version or use [gitter](https://gitter.im/ngx-super-table).
